version = 0.1

[default.deploy.parameters]
stack_name = "shortlistme-backend"
resolve_s3 = true
s3_prefix = "shortlistme-backend"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
